apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: my-acme-netpol
spec:
  podSelector:
    matchLabels:
      app: my-acme-website
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 80
