name: Simple-Web-Deploy
on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .

      - name: Quality Check (The Inspector)
        run: |
          echo "Checking if index.html exists..."
          ls index.html
          echo "Checking for forbidden words..."
          ! grep "TODO" index.html
